export enum Permission {
  VIEW_CAMPAIGNS = 'VIEW_CAMPAIGNS',
  CREATE_CAMPAIGN = 'CREATE_CAMPAIGN',
  UPDATE_OWN_CAMPAIGN = 'UPDATE_OWN_CAMPAIGN',
  DELETE_OWN_CAMPAIGN = 'DELETE_OWN_CAMPAIGN',
  UPDATE_ANY_CAMPAIGN = 'UPDATE_ANY_CAMPAIGN',
  DELETE_ANY_CAMPAIGN = 'DELETE_ANY_CAMPAIGN',
  APPROVE_CAMPAIGN = 'APPROVE_CAMPAIGN',
  REJECT_CAMPAIGN = 'REJECT_CAMPAIGN',

  CONTRIBUTE_TO_CAMPAIGN = 'CONTRIBUTE_TO_CAMPAIGN',

  READ_COMMENTS = 'READ_COMMENTS',
  WRITE_COMMENT = 'WRITE_COMMENT',
  MODERATE_COMMENTS = 'MODERATE_COMMENTS',

  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_ROLES = 'MANAGE_ROLES',

  MANAGE_PLATFORM_SETTINGS = 'MANAGE_PLATFORM_SETTINGS',

  MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS',
}

